  
  #ifndef PANORAMA_CONST
#define  PANORAMA_EQUIRECTANGULAR  0
#define  PANORAMA_FISHEYE_EQUIDISTANT  1
#define  PANORAMA_FISHEYE_EQUISOLID  2
#define  PANORAMA_MIRRORBALL 3
#define  PANORAMA_NUM_TYPES  4
  #endif