message(STATUS "cmake custom flag build")
set(VCPKG_FORCE_SYSTEM_BINARIES 1)
set(VCPKG_VISUAL_STUDIO_PATH "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community")


set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)
set(CHARSET_FLAG "/utf-8")
set(VCPKG_PLATFORM_TOOLSET 142)
set(VCPKG_CXX_FLAGS "-D_ITERATOR_DEBUG_LEVEL=0") 
set(VCPKG_CXX_FLAGS_RELEASE "-D_ITERATOR_DEBUG_LEVEL=0")
set(VCPKG_C_FLAGS_RELEASE "-D_ITERATOR_DEBUG_LEVEL=0")
set(VCPKG_CXX_FLAGS_DEBUG "-D_ITERATOR_DEBUG_LEVEL=0")
set(VCPKG_C_FLAGS_DEBUG "-D_ITERATOR_DEBUG_LEVEL=0")
#set(VCPKG_LINKER_FLAGS_RELEASE "/OPT:ICF=3 /LTCG")




message(STATUS  "vcpkg_configure_cmake +CXX_FLAGS [ ${VCPKG_CXX_FLAGS_DEBUG} ]")